<?php return array(

'B' => 'Pogrubienie',
'U' => 'Podkreślenie',
'I' => 'Kursywa',
'LEFT' => 'Do lewej',
'CENTER' => 'Wycentruj',
'RIGHT' => 'Do prawej',
'JUSTIFY' => 'Wyjustuj',
'PRE' => 'Tekst preformatowany',
'HR' => 'Linia pozioma',
'LIST' => 'Lista',
'CODE' => 'Kod',
'QUOTE' => 'Cytat',
'SUP' => 'Indek górny',
'SUB' => 'Indeks dolny',
'IMG' => 'Obrazek',
'URL' => 'Odnośnik',
'EMAIL' => 'E-mail',
'SIZE' => 'Rozmiar czcionki',
'COLOR' => 'Kolor czcionki',
'FONT' => 'Czcionka',
'EMOTICONS' => 'Emotikony',
'PREVIEW' => 'Podgląd',
'INCREASE_TEXTAREA' => 'Powiększ pole tekstowe',
'DECREASE_TEXTAREA' => 'Pomniejsz pole tekstowe');