SQL Standard
CREATE TABLE users
(
	uid INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nickname VARCHAR(150) NOT NULL,
	logname VARCHAR(100) NOT NULL,

	email VARCHAR(100) NOT NULL,
	registration_email VARCHAR(100) NOT NULL,
	pass CHAR(32) NOT NULL,
	gid TINYINT(3) UNSIGNED,
	
	created INT(11) UNSIGNED NOT NULL,
	access INT(11) UNSIGNED NOT NULL,
	logged  INT(11) UNSIGNED NOT NULL,
	
	forename VARCHAR(100),
	surname VARCHAR(100),
	gender TINYINT(1) UNSIGNED,
	locality VARCHAR(100),
	country CHAR(2),
	communicator VARCHAR(50),
	website VARCHAR(100),
	birthdate CHAR(10),
	newsletter TINYINT(1) UNSIGNED DEFAULT 1,
	pm_notify TINYINT(1) UNSIGNED DEFAULT 1,
	hide_email TINYINT(1) UNSIGNED DEFAULT 0,
	avatar VARCHAR(255),
	photo VARCHAR(255),
	title VARCHAR(100),
	interests VARCHAR(100),
	signature TEXT,
	hidden TINYINT(1) UNSIGNED DEFAULT 0,
	blocked TINYINT(1) UNSIGNED DEFAULT 0,
	points INT(10) NOT NULL DEFAULT 0,
	warnings TINYINT(2) UNSIGNED DEFAULT 0,
	pm_new SMALLINT(5) UNSIGNED DEFAULT 0,
	pm_inbox SMALLINT(5) UNSIGNED DEFAULT 0,
	pm_outbox SMALLINT(5) UNSIGNED DEFAULT 0,
	visits INT(10) UNSIGNED DEFAULT 0,
	time_offset FLOAT(6) DEFAULT 0,
	--last_visit INT(11) UNSIGNED,
	last_path VARCHAR(250),
	ip CHAR(15),
	auth_code CHAR(16) NOT NULL,
	login_attemps TINYINT(2),
	agent VARCHAR(250),
	permits TEXT,
	params TEXT,
	UNIQUE KEY (nickname, logname, email, auth_code)
);

blocked:
0/NULL - uzytkownik jest aktywny
1 - konto jest nieaktywne
2 - uzytkownik jest zbanowany

parameters:
points:0
posts:0
topics:0
comments:0
advertisements/announcements:0


CREATE TABLE " . TABLE_PREFIX . "user (
	userid INT UNSIGNED NOT NULL AUTO_INCREMENT,
	usergroupid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	membergroupids CHAR(250) NOT NULL DEFAULT '',
	displaygroupid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	username VARCHAR(100) NOT NULL DEFAULT '',
	password CHAR(32) NOT NULL DEFAULT '',
	passworddate date NOT NULL DEFAULT '0000-00-00',
	email CHAR(100) NOT NULL DEFAULT '',
	styleid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	parentemail CHAR(50) NOT NULL DEFAULT '',
	homepage CHAR(100) NOT NULL DEFAULT '',
	icq CHAR(20) NOT NULL DEFAULT '',
	aim CHAR(20) NOT NULL DEFAULT '',
	yahoo CHAR(32) NOT NULL DEFAULT '',
	msn CHAR(100) NOT NULL DEFAULT '',
	skype CHAR(32) NOT NULL DEFAULT '',
	showvbcode SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	showbirthday SMALLINT UNSIGNED NOT NULL DEFAULT '2',
	usertitle CHAR(250) NOT NULL DEFAULT '',
	customtitle SMALLINT NOT NULL DEFAULT '0',
	joindate INT UNSIGNED NOT NULL DEFAULT '0',
	daysprune SMALLINT NOT NULL DEFAULT '0',
	lastvisit INT UNSIGNED NOT NULL DEFAULT '0',
	lastactivity INT UNSIGNED NOT NULL DEFAULT '0',
	lastpost INT UNSIGNED NOT NULL DEFAULT '0',
	lastpostid INT UNSIGNED NOT NULL DEFAULT '0',
	posts INT UNSIGNED NOT NULL DEFAULT '0',
	reputation INT NOT NULL DEFAULT '10',
	reputationlevelid INT UNSIGNED NOT NULL DEFAULT '1',
	timezoneoffset CHAR(4) NOT NULL DEFAULT '',
	pmpopup SMALLINT NOT NULL DEFAULT '0',
	avatarid SMALLINT NOT NULL DEFAULT '0',
	avatarrevision INT UNSIGNED NOT NULL DEFAULT '0',
	profilepicrevision INT UNSIGNED NOT NULL DEFAULT '0',
	sigpicrevision INT UNSIGNED NOT NULL DEFAULT '0',
	options INT UNSIGNED NOT NULL DEFAULT '15',
	birthday CHAR(10) NOT NULL DEFAULT '',
	birthday_search DATE NOT NULL DEFAULT '0000-00-00',
	maxposts SMALLINT NOT NULL DEFAULT '-1',
	startofweek SMALLINT NOT NULL DEFAULT '1',
	ipaddress CHAR(15) NOT NULL DEFAULT '',
	referrerid INT UNSIGNED NOT NULL DEFAULT '0',
	languageid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	emailstamp INT UNSIGNED NOT NULL DEFAULT '0',
	threadedmode SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	autosubscribe SMALLINT NOT NULL DEFAULT '-1',
	pmtotal SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	pmunread SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	salt CHAR(3) NOT NULL DEFAULT '',
	ipoints INT UNSIGNED NOT NULL DEFAULT '0',
	infractions INT UNSIGNED NOT NULL DEFAULT '0',
	warnings INT UNSIGNED NOT NULL DEFAULT '0',
	infractiongroupids VARCHAR (255) NOT NULL DEFAULT '',
	infractiongroupid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	adminoptions INT UNSIGNED NOT NULL DEFAULT '0',
	profilevisits INT UNSIGNED NOT NULL DEFAULT '0',
	friendcount INT UNSIGNED NOT NULL DEFAULT '0',
	friendreqcount INT UNSIGNED NOT NULL DEFAULT '0',
	vmunreadcount INT UNSIGNED NOT NULL DEFAULT '0',
	vmmoderatedcount INT UNSIGNED NOT NULL DEFAULT '0',
	socgroupinvitecount INT UNSIGNED NOT NULL DEFAULT '0',
	socgroupreqcount INT UNSIGNED NOT NULL DEFAULT '0',
	pcunreadcount INT UNSIGNED NOT NULL DEFAULT '0',
	pcmoderatedcount INT UNSIGNED NOT NULL DEFAULT '0',
	gmmoderatedcount INT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (userid),
	KEY usergroupid (usergroupid),
	KEY username (username),
	KEY birthday (birthday, showbirthday),
	KEY birthday_search (birthday_search),
	KEY referrerid (referrerid)
);
